spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: Teddy2008!
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
